### ISSUE TITLE
'DistMultModule' object has no attribute 'margin'

### ISSUE THREAD

**Issue by zqqQiu** [WeidongLi-KG/KBGAN_PyTorch-v0.4.1#2]
AttributeError: 'DistMultModule' object has no attribute 'margin'

**Comment by WeidongLi-KG** [comment]
> AttributeError: 'DistMultModule' object has no attribute 'margin'

You need to modify the corresponding configuration file.

**Comment by zqqQiu** [comment]
how to modify the configuration file?Is the attribute margin added to the distimult in distmult.py and config_fb15k237?
